---
name: "Update CLI Reference Docs"

on:
  workflow_dispatch:
  schedule:
    # Run this job every Monday and Wednesday at 00:00
    - cron: '0 0 * * 1,3'

permissions:
  contents: write
  pull-requests: write

jobs:
  cli-ref-docs:
    name: Update CLI Reference Docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout docs
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Updatecli Binary
        uses: updatecli/updatecli-action@cf942226b953240efac9ff60bf42df2b908c2fa0 # v2.83.0

      - name: Run Updatecli to update CLI Reference Docs
        run: "updatecli compose apply --file updatecli/update-cli-ref-docs.yaml"
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
