---
name: "Updatecli: Dependency Management"

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 * * * *"

permissions:
  contents: write
  pull-requests: write

jobs:
  updatecli:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.4.4
        with:
          node-version: 20.x

      #  https://github.com/actions/setup-node/issues/490
      - name: Repair NPM # Update to latest npm and yarn
        run: "npm install -g npm yarn"

      - name: Install Dependencies
        run: "yarn install --frozen-lockfile"

      - name: Install Updatecli Binary
        uses: updatecli/updatecli-action@cf942226b953240efac9ff60bf42df2b908c2fa0 # v2.83.0

      - name: Run Updatecli in enforce mode
        run: "updatecli compose apply --experimental --file updatecli/updatecli-compose.yaml"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
